fix: Only change background sound if finish onboarding
TeamLetrando/SoundsKit pull request #5
Opened 2021-11-04 14:58 UTC by patysiq

2021-11-08 11:25 UTC, ronaldogomes96 requested changes

2021-11-08 11:25 UTC, ronaldogomes96 commented on Sources/SoundsKit/SoundsKit.swift
> +import SwiftUI
É usado SwiftUI? kkkk

2021-11-08 11:25 UTC, ronaldogomes96 commented on Tests/SoundsKitTests/SoundsKitTests.swift
> +        let sut = 1
a variável sut não deve ser uma variável computada e sim a classe sobre teste. Colocando dessa forma fica ambíguo e confuso pois perde a identidade da nomenclatura dos testes unitários. Deve-se trocar o nome dessa variável para um nome mais correspondente a este numero 1

2021-11-08 11:25 UTC, ronaldogomes96 commented on Tests/SoundsKitTests/SoundsKitTests.swift
> +        let sut = 3
Mesmo comentario do teste anterior.

2021-11-08 11:25 UTC, ronaldogomes96 commented on Tests/SoundsKitTests/SoundsKitTests.swift
> +        let sut = 1
Mesma questão do anterior

2021-11-08 20:46 UTC, patysiq commented on Sources/SoundsKit/SoundsKit.swift
> +import SwiftUI
Sorry 😜

2021-11-08 23:02 UTC, ronaldogomes96 approved these changes

2021-11-09 11:33 UTC, lidianegb approved these changes

2021-11-09 11:42 UTC, merged